### ISSUE TITLE
allusion to waterfall

### ISSUE THREAD

**Issue by eliasmalik** [foundersandcoders/ws-github-api#14]
> What different ways can you think of structuring your code? And what are the advantages of each? (think back to things you learnt last week too! 💧 => 💧 => 💧)

This allusion to waterfall doesn't make sense for the current curriculum.

**Comment by emilyb7** [comment]
@eliascodes sorry I realise you wrote this months ago and have probably forgotten about it...

I'm happy to just remove the bits that you've quoted above if you think that's better?

There's still a solution using waterfall on the solutions branch, which students can take a look at if they're interested...

**Comment by eliasmalik** [comment]
Yeah I think that's the only reference I found 👍
