### ISSUE TITLE
Rename solution_simple

### ISSUE THREAD

**Issue by ameliejyc** [foundersandcoders/ws-github-api#21]
Could it just be called solution instead? It's not that simple and we don't want to put anyone off 👍

**Comment by emilyb7** [comment]
@ameliejyc sure, feel free to make a PR. Same for any changes to the solution that could make it _more_ simple. Hope teaching today went well?

**Comment by ameliejyc** [comment]
Oh no I tried but I'm getting this error:

> remote: Permission to emilyb7/workshop-APIs.git denied to ameliejyc.
> fatal: unable to access 'https://github.com/emilyb7/workshop-APIs.git/': The requested URL returned error: 403

It might be an issue with me or the repo, I can't tell. 

Teaching was good thanks! Unfortunately Github and then the internet went down during this workshop though... less than ideal 😅

**Comment by emilyb7** [comment]
You need to accept my invitation to collaborate on the repo! I'll resend it now...

**Comment by ameliejyc** [comment]
Done!
