### ISSUE TITLE
access token permissions

### ISSUE THREAD

**Issue by Jbarget** [foundersandcoders/ws-github-api#8]
instructions on which permissions to allow for the access token would be good, we had a few students wondering about which scopes to choose for the access_token

**Comment by emilyb7** [comment]
@Jbarget thanks for this. I think i'm gonna take out the access token thing altogether. A couple of students in London got rate limited even when using it so I'm not sure it's a suitable solution.

By spreading everyone across 2 wifi networks, we managed to get round the problem. 

Code Your Future apparently use a proxy for their API workshops => https://github.com/Code-Your-Future/api-proxies

This might be something to look into if this workshop is run again in the future
